---
title: "LATAM project results"
output:
  html_document:
    df_print: paged
  html_notebook:
    code_folding: hide
---

```{r include = FALSE}
library(viridis)
library(tidyverse)
library(geomtextpath)
library(countrycode)
library(gridExtra)
library(stats)
library(ggbump)
library(GGally)
library(openxlsx)
options(dplyr.summarise.inform = FALSE)
```

```{r, include=FALSE}

paper_level_tables <- readRDS('results/paper_level_tables_1990.RDS')

latam_meta <- read_delim("data/latam/latam_meta_1990.csv", 
                         delim = ";", escape_double = FALSE, 
                         col_names = c('Pub_ID', 'pub_year','source_title', 'source_type',
                                      'level1', 'level2', 'n_cits'), 
                         trim_ws = TRUE
                         
)  %>% 
   select('Pub_ID','level1','level2', 'pub_year') %>% 
                  distinct(Pub_ID, .keep_all = TRUE) %>% 
  #There is too much missing information in this two cases
  filter(!Pub_ID %in%c("pub.1107816940","pub.1134957943"))


latam_meta<- latam_meta%>% 
  mutate(level1 = str_to_title(substr(level1, 3, nchar(level1))))%>% 
  mutate(level2 = str_to_title(substr(level2, 6, nchar(level2))))

latam_country_codes <- c('AR','BO','BR','CL','CO','MX','PY','PE','UY','VE')

latam_authors <- readRDS("data/latam/latam_authors_1990.RDS")

aux_journal_country <- readRDS("results/aux_journal_country_1990.RDS")%>% 
  select(-journal_country) %>% 
  unique()

aux_conference_country <- readRDS("results/aux_conference_country_1990.RDS") %>% 
  select(-proc_country) %>% 
  unique() %>% 
  rename("latam_journal" = "latam_conf") %>% 
  janitor::clean_names()

journal_aux <- bind_rows(aux_journal_country,aux_conference_country) %>% unique()

```

```{r, include=FALSE}

document_topics <- read_csv("code/job_outputs/bertopic_output_20240302_195213/document_topics.csv")

topic_info <- read_csv("code/job_outputs/bertopic_output_20240302_195213/topic_info.csv")

topic_labels <- topic_info %>% 
  janitor::clean_names() %>% 
  mutate(name = gsub("_"," ",name)) %>% 
  mutate(name = ifelse(topic <1000,
                       ifelse(topic <100, 
                       substr(name, 3, nchar(name)),
                       substr(name, 4, nchar(name))),
                       substr(name, 5, nchar(name)))
         ) %>% 
  mutate(name = str_squish(name)) %>% 
  mutate(label = paste(word(name,1),word(name,2)))

```

```{r periods}
period1 <- c(1993:2002)
name_period1 <- "1993-2002"
period2 <- c(2003:2012)
name_period2 <- "2003-2012"
period3 <- c(2013:2022)
name_period3 <- "2013-2022"

latam_meta<- latam_meta %>% 
  mutate(period = factor(case_when(pub_year %in% period1 ~ paste0(name_period1),
                                   pub_year %in% period2 ~ paste0(name_period2),
                                   pub_year %in% period3 ~ paste0(name_period3)),
                         levels = c(name_period1,name_period2,name_period3))) %>% 
  filter(!is.na(period))

```


## Context: gender and disciplines

```{r fig1_table}
fig1_table <- latam_meta %>% 
  inner_join(.,(paper_level_tables$aux_gender_props),
             by="Pub_ID") %>% 
  inner_join(.,(paper_level_tables$aux_number_authors),
             by="Pub_ID") %>%
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) 

```



```{r fractionalized_version}
ffig1a_table <- latam_meta %>% 
  inner_join(.,(paper_level_tables$paper_gender_dist),
             by="Pub_ID") %>% 
  inner_join(.,(paper_level_tables$aux_number_authors),
             by="Pub_ID") %>%
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id"))

```


```{r}
ffig1b_table <- latam_meta %>% 
  left_join(.,(latam_authors),
             by="Pub_ID") %>% 
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(gender %in% c("Men","Women")) %>% 
  select(Pub_ID,period,pub_year,author_id,gender) %>% 
  unique()
```




```{r}
plot_a <- ffig1b_table%>% 
  filter(!is.na(period)) %>% 
  group_by(pub_year) %>% 
  summarise(Women =n_distinct(author_id[gender=="Women"]),
            n = n_distinct(author_id)) %>% 
  ungroup() %>% 
  mutate("Women authors" = Women/n) %>% 
  select(-Women,-n) %>% 
  left_join(.,
(ffig1a_table%>% 
  filter(!is.na(period)) %>% 
  group_by(pub_year) %>% 
  summarise("Women authorship" =mean(Women)) )) %>% 
  pivot_longer(!pub_year, names_to = "ind", values_to = "value") %>% 
  
  ggplot(.,aes(y=value,x=as.numeric(pub_year),group = ind,color = ind))+
  geom_line()+
  #geom_point()+
  geom_vline(aes(xintercept = 2003), size = .2, linetype = "longdash",alpha=.5)+
  geom_vline(aes(xintercept = 2012), size = .2, linetype = "longdash",alpha=.5)+
  theme_minimal()+
  theme(legend.position = "bottom")+
  theme(text = element_text(size = 7))+
  scale_color_viridis(discrete = TRUE,option = "F", begin = .2, end =.5)+
  scale_y_continuous(labels = function(x) paste0(x*100,"%"))+
  labs(x = "Publication year", 
       y = "Women authors / \n Women authorship",
       color = "",
       title = "A"
       )+
  #geom_hline(yintercept = .5, size=.1)+
  guides(fill = guide_legend(reverse=TRUE))


```

```{r gap}

#Gap between regional and global circuits in women authorship

bind_rows(
  (ffig1a_table%>% 
     filter(latam_journal == "Non Latin American journal") %>% 
     filter(!is.na(period)) %>% 
     group_by(pub_year) %>% 
     summarise("Women authorship" =mean(Women)) %>% 
     mutate(circuit = "Global")),
  
  (ffig1a_table%>% 
     filter(latam_journal == "Latin American journal") %>% 
     filter(!is.na(period)) %>% 
     group_by(pub_year) %>% 
     summarise("Women authorship" =mean(Women)) %>% 
     mutate(circuit = "Regional"))) %>% 
  
  pivot_wider(id_cols =pub_year, names_from = circuit, values_from = `Women authorship` ) %>% 
  mutate(gap = (Regional-Global)/Regional) #%>% 
  #summarise(mean(gap))

aggregate <- ffig1a_table %>% 
  filter(!is.na(latam_journal)) %>% 
  group_by(latam_journal) %>% 
  summarise("Women authorship" =mean(Women)) 

(aggregate[1,2] - aggregate[2,2])/aggregate[1,2]


```


```{r}
plot_b <- fig1_table%>% 
    filter(!is.na(period)) %>% 
  filter(!is.na(latam_journal)) %>% 
  group_by(pub_year) %>% 
  summarise(n =n_distinct(Pub_ID),
            n_journal = n_distinct(Pub_ID[latam_journal=="Latin American journal"])
  ) %>% 
  mutate(p_journal = n_journal/n ) %>% 
 
  ggplot(.,aes(y=p_journal,x=as.numeric(pub_year)  ))+
  geom_line()+
   geom_vline(aes(xintercept = 2003), size = .2, linetype = "longdash",alpha=.5)+
  geom_vline(aes(xintercept = 2012), size = .2, linetype = "longdash",alpha=.5)+
  theme_minimal()+
  theme(legend.position = "top")+
  theme(text = element_text(size =7))+
  scale_color_viridis(discrete = TRUE,option = "F", begin = .6, end =.8)+
  scale_y_continuous(labels = function(x) paste0(x*100,"%"))+
  labs(y = "Published in Latin American \n journals or conferences",
       x = "Publication year", fill = "",
       title= "B")
```

```{r fig.width=4,fig.height=5}
grid.arrange(plot_a, plot_b, ncol=1)
```


### Insertion in LatAm circuit


```{r expected}
#%journal by discipline
exp_1 <- paper_level_tables$paper_gender_dist %>% 
    left_join(.,latam_meta, by = "Pub_ID") %>% 
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(!is.na(level1)) %>% 
  filter(!is.na(level2)) %>% 
  filter(!is.na(latam_journal)) %>% 
  group_by(level2,period) %>% 
  summarise(n =n_distinct(Pub_ID),
            n_journal = n_distinct(Pub_ID[latam_journal=="Latin American journal"])) %>% 
  ungroup() %>% 
  mutate(p_journal = n_journal/n
         ) %>% 
  select(-n,-n_journal)

#gender dist by discipline
exp_2 <- paper_level_tables$paper_gender_dist %>% 
    left_join(.,latam_meta, by = "Pub_ID") %>% 
   left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(!is.na(latam_journal)) %>% 
  filter(!is.na(level1)) %>% 
  filter(!is.na(level2)) %>% 
  group_by(level2,period) %>% 
  summarise(Men =sum(Men),
            Women =sum(Women)) %>% 
  pivot_longer(.,!c("level2","period"), names_to = "gender", values_to = "n") %>% 
  group_by(gender,period) %>% 
  mutate(n = n/sum(n))

exp_3 <-  exp_2 %>% 
  left_join(.,exp_1) %>% 
  mutate(expected = n*p_journal) %>% 
  group_by(gender,period) %>% 
  summarize(exp = sum(expected))

```

```{r real}
real_1 <- paper_level_tables$paper_gender_dist %>% 
    left_join(.,latam_meta, by = "Pub_ID") %>% 
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(!is.na(level1)) %>% 
  filter(!is.na(level2)) %>% 
  filter(!is.na(latam_journal)) %>% 
  group_by(period,
           latam_journal) %>% 
  summarise(Men =sum(Men),
            Women =sum(Women)) %>% 
  pivot_longer(.,!c("period",
                    "latam_journal"), names_to = "gender", values_to = "n") %>% 
  group_by(period,
           gender) %>% 
  mutate(n = n/sum(n)) %>% 
  filter(latam_journal == "Latin American journal") %>% 
  select(-latam_journal) %>% 
  rename("real" = "n")
```

```{r real_exp, fig.height=4}
real_1 %>% 
  left_join(.,exp_3) %>% 
  mutate(rel = real/exp -1) %>% 
  rename("Real" = "real",
         "Expected" = "exp",
         "Real/Expected" = "rel") %>% 
  pivot_longer(!c("gender","period"), names_to = "ind", values_to = "value") %>% 
  filter(ind == "Real/Expected") %>% 
  
  ggplot(.,aes(x=gender,y= value,fill =period))+
  geom_col(position = "dodge")+
  #facet_wrap(~ind, scales = "free")+
  theme_minimal()+
  theme(legend.position = "none")+
  theme(text = element_text(size = 10),
        axis.title.y = element_text(size = 7))+
  scale_fill_viridis(discrete = TRUE,option = "G", begin = .2, end =.8)+
  labs(y = "Ratio between real and expected % of publications \n in Latin American journals or conferences",
       #"Real/Expected - 1 \n % of articles published in Latin American journals",
       x = "",
       title = "")+
  geom_hline(yintercept = 0,size=.5)+
  facet_wrap(~period)
  
```

```{r cont_disc}

#continuous version
exp_1 <- paper_level_tables$paper_gender_dist %>% 
  left_join(.,latam_meta, by = "Pub_ID") %>% 
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(!is.na(level1)) %>% 
  filter(!is.na(level2)) %>% 
  filter(!is.na(latam_journal)) %>% 
  group_by(level2,pub_year) %>% 
  summarise(n =n_distinct(Pub_ID),
            n_journal = n_distinct(Pub_ID[latam_journal=="Latin American journal"])) %>% 
  ungroup() %>% 
  mutate(p_journal = n_journal/n
  ) %>% 
  select(-n,-n_journal)

#gender dist by discipline
exp_2 <- paper_level_tables$paper_gender_dist %>% 
  left_join(.,latam_meta, by = "Pub_ID") %>% 
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(!is.na(latam_journal)) %>% 
  filter(!is.na(level1)) %>% 
  filter(!is.na(level2)) %>% 
  group_by(level2,pub_year) %>% 
  summarise(Men =sum(Men),
            Women =sum(Women)) %>% 
  pivot_longer(.,!c("level2","pub_year"), names_to = "gender", values_to = "n") %>% 
  group_by(gender,pub_year) %>% 
  mutate(n = n/sum(n))

exp_3 <-  exp_2 %>% 
  left_join(.,exp_1) %>% 
  mutate(expected = n*p_journal) %>% 
  group_by(gender,pub_year) %>% 
  summarize(exp = sum(expected))


real_1 <- paper_level_tables$paper_gender_dist %>% 
  left_join(.,latam_meta, by = "Pub_ID") %>% 
  left_join(.,journal_aux, by = c("Pub_ID" = "pub_id")) %>% 
  filter(!is.na(level1)) %>% 
  filter(!is.na(level2)) %>% 
  filter(!is.na(latam_journal)) %>% 
  group_by(pub_year,
           latam_journal) %>% 
  summarise(Men =sum(Men),
            Women =sum(Women)) %>% 
  pivot_longer(.,!c("pub_year",
                    "latam_journal"), names_to = "gender", values_to = "n") %>% 
  group_by(pub_year,
           gender) %>% 
  mutate(n = n/sum(n)) %>% 
  filter(latam_journal == "Latin American journal") %>% 
  select(-latam_journal) %>% 
  rename("real" = "n")


```

